turbine: "osw_17MW"
installation_availability: 0.7 # 30% downtime during installation to match ORCA
site:
  area: 142 # km^2
  depth: 45  # m - this value is overridden by greenheart config
  distance: 141.5414 # km
  distance_to_landfall: 44.74089 # km
  mean_windspeed: False #8.45863584474886 # required input for ORBIT, provide desired mean wind speed or set to False to give ORBIT the mean wind speed from the lat/lon selection
plant:
  capacity: 986 # MW
  layout: grid
  num_turbines: 58 # needs to be changed based on turbine model - this value is overridden by greenheart config
  row_spacing: 7 # rotor diameters # based on rule of thumb of 7D - this value is overridden by greenheart config
  substation_distance: 1 # from ORBIT/examples/configs/example_fixed_project.yaml
  turbine_spacing: 7 # rotor diameters # original 10 - this value is overridden by greenheart config
landfall:
  interconnection_distance: 5 # km
  trench_length: 4 # km
# port:
#   monthly_rate: 2000000.0 # USD
#   sub_assembly_lines: 1
#   turbine_assembly_cranes: 1
# Vessels
array_cable_install_vessel: example_cable_lay_vessel # from ORBIT/examples/configs/example_fixed_project.yaml
export_cable_install_vessel: example_cable_lay_vessel # from ORBIT/examples/configs/example_fixed_project.yaml
#export_cable_bury_vessel: example_cable_lay_vessel # from ORBIT/examples/configs/example_fixed_project.yaml
oss_install_vessel: example_heavy_lift_vessel # from ORBIT/examples/configs/example_fixed_project.yaml
spi_vessel: example_scour_protection_vessel # from ORBIT/examples/configs/example_fixed_project.yaml
wtiv: example_wtiv # from ORBIT/examples/configs/example_fixed_project.yaml
# Module Specific
OffshoreSubstationInstallation:
  feeder: example_heavy_feeder # from ORBIT/examples/configs/example_fixed_project.yaml
  num_feeders: 1 # from ORBIT/examples/configs/example_fixed_project.yaml
array_system:
  free_cable_length: 0.5
array_system_design:
  cables:
  - XLPE_185mm_66KV 
  - XLPE_630mm_66KV
export_system_design:
  cables: 
  # - HVDC_2000mm_320kV # as done for OSW HVDC
  - XLPE_1000m_220kV # HVAC
  percent_added_length: 0.1 # ORBIT/WISDEM default
scour_protection_design:
  cost_per_tonne: 40 # OSW
  scour_protection_depth: 1 # ORBIT default
MonopileDesign:
  monopile_steel_cost: 3500 # USD/t ORBIT new inputs
  tp_steel_cost: 4500 # USD/t ORBIT new inputs
# Configured Phases 
design_phases:
- ArraySystemDesign # from ORBIT/examples/configs/example_fixed_project.yaml
- MonopileDesign # from ORBIT/examples/configs/example_fixed_project.yaml
# - JacketDesign # Jacket not ready yet in ORBIT
- ScourProtectionDesign # from ORBIT/examples/configs/example_fixed_project.yaml
- ElectricalDesign # new addition from Sophie Bradenkamp combined ExportSystemDesign and OffshoreSubstationDesign phases

install_phases: # based on Fig. B-7 in https://www.boem.gov/sites/default/files/environmental-stewardship/Environmental-Studies/Renewable-Energy/Phased-Approaches-to-Offshore-Wind-Developments-and-Use-of-Project-Design-Envelope.pdf
  MonopileInstallation: 0 # from ORBIT/examples/configs/example_fixed_project.yaml
  ExportCableInstallation: 0  # from ORBIT/examples/configs/example_fixed_project.yaml
  ScourProtectionInstallation: !!python/tuple # from ORBIT/examples/configs/example_fixed_project.yaml
  - MonopileInstallation
  - 0.1 # start scour protection installation when 10 % of the MPs have bee installed
  OffshoreSubstationInstallation: 0 # from ORBIT/examples/configs/example_fixed_project.yaml
  ArrayCableInstallation: !!python/tuple # from ORBIT/examples/configs/example_fixed_project.yaml
  - MonopileInstallation
  - 0.2 # start array cable installation when 20% of monopiles have been installed
  TurbineInstallation: !!python/tuple # from ORBIT/examples/configs/example_fixed_project.yaml
  - MonopileInstallation
  - 0.3 # start WTG installation when 30% of the monopiles have been installed
  # JacketInstallation: 0 # Jacket not ready yet in ORBIT

# Wind Project Inputs
project_parameters:
  turbine_capex: 1500 # $USD turbine CAPEX only as per discussion with Matt Shields 
  opex_rate: 53.25648 #osw national analysis, $USD/kW/yr ATB 2022, OpEx based on R&D assumptions with a base year of 2022. ATB https://atb.nrel.gov/electricity/2022/offshore_wind
  # commissioning: 0.01 # ORBIT default
  # decommissioning: 0.15 # ORBIT default
  # project_lifetime: 30 # 2022 ATB capital recovery period for offshore wind