# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

  # Generate the Sphinx configuration for Jupyter Book so it builds
  jobs:
    pre_build:
      - "jupyter-book config sphinx docs/"

# Set the build to use dependencies in pyproject.toml
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - develop