# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2
sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "18"  # add Node.js for the doc build (choose version as needed)

  # Generate the Sphinx configuration for Jupyter Book so it builds
  jobs:
    pre_build:
      - "jupyter-book config sphinx docs/"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - develop
