# Site + Plant Parameters - production start around 2027/2028
# Central Atlantic (Call Area E) - Floating
# lengths in m
turbine: "osw_12MW"
wind:
  flag: True
  performance_model: "floris"
pv:
  flag: True
  system_capacity_kw: 10000 # TODO stop this number from printing when HOPP is run
  opex_rate: 15.5 #$/kw/yr based on the https://www.nrel.gov/docs/fy22osti/80695.pdf
  #solar_cost_kw: 1290 #$/kw based on the https://www.nrel.gov/docs/fy22osti/80695.pdf
PVCosts:
    SiteStaging: 0
    Module: 330 #$/kW
    Inverter: 40
    StructuralBOS: 370
    ElectricalBOS: 100
    InstallationandLabour: 60
    EPCoverhead: 80
    permitingInspectionandinterconnection: 50
    shippingHandeling: 20
    salestax: 40
    Contingency: 60
    Developeroverhead: 70
    EPCDevProfit: 70
wave:
  flag: True
  device_rating_kw: 286 # TODO stop this number from printing when HOPP is run
  num_devices: 100
  #wave_cost_kw: 13600 # $/kw based on the https://energy.sandia.gov/wp-content/gallery/uploads/SAND2014-9040-RMP-REPORT.pdf
  #opex_rate: 192 # $/kw/yr based on the https://energy.sandia.gov/wp-content/gallery/uploads/SAND2014-9040-RMP-REPORT.pdf
WaveCost:
    reference_model_num: 0
    distance_to_shore: 0 #for wave module
    number_rows: 10
    device_spacing: 200 
    row_spacing: 200
    cable_system_overbuild: 10
    structural_assembly_cost_kw: 6946.84
    power_takeoff_system_cost_kw: 1538.96
    mooring_found_substruc_cost_kw: 1837.40
    development_cost_kw: 578.2
    eng_and_mgmt_cost_kw: 197.76
    assembly_and_install_cost_kw: 897.05
    other_infrastructure_cost_kw: 0
    array_cable_system_cost_kw:  448.03
    export_cable_system_cost_kw: 56.06
    onshore_substation_cost_kw: 0
    offshore_substation_cost_kw: 100
    other_elec_infra_cost_kw: 71.25
battery:
  flag: False
atb_year: 2025 # as per discussions of operational by 2027. This also makes the estimates a little more conservative
cost_year: 2022 # to match ATB
installation_availability: 0.7 # 30% downtime during installation to match ORCA
wind_resource_year: 2013
project_location:
  lat: 37.48358 #
  lon: -73.72925 # 
site:
  depth: 1300 # m Site actually located at 2000m but only 600-1300m depth works with SemiTaut Mooring Design.
  distance: 110 # km
  distance_to_landfall: 110 # km
  mean_windspeed: False #9.499538812785387 # m/s
plant:
  capacity: 996 # MW Wind only as this is used in orbit to cross verify
  layout: grid
  num_turbines: 83 # needs to be changed based on turbine model
  row_spacing: 7 # rotor diameters 
  substation_distance: 1 # from ORBIT/examples/configs/example_fixed_project.yaml
  turbine_spacing: 7 # rotor diameters 

landfall:
  interconnection_distance: 5 # onshore spur line = dist_l_to_ts from ORCA
  trench_length: 4

port:
  monthly_rate: 2000000.0
  sub_assembly_lines: 3
  turbine_assembly_cranes: 3
  num_cranes : 3
# Vessels
array_cable_install_vessel: example_cable_lay_vessel # from ORBIT/examples/configs/example_fixed_project.yaml
array_system:
  free_cable_length: 0.5
export_cable_install_vessel: example_cable_lay_vessel
# export_cable_bury_vessel: example_cable_lay_vessel
# Assume the dynamic cables will be suspended in the water column (not buried)
mooring_install_vessel: example_support_vessel
ahts_vessel: example_ahts_vessel
oss_install_vessel: example_support_vessel # assume that this is towed out with a anchor handling vessel
# spi_vessel: example_large_scour_protection_vessel  # Define a custom vessel in analysis repo (data/vessels) since standard SPI vessel isn't big enough for 15 MW turbine scour
# Scour protection installation (SPI) vessel only for fixed bottom foundations to prevent erosion at seabed
support_vessel: example_support_vessel
towing_vessel: example_towing_vessel
towing_vessel_groups:
  ahts_vessels: 1
  station_keeping_vessels: 1
  towing_vessels: 2
  num_groups: 3 # note these numbers are different than the default for ORBIT- I believe ORCA assumes only one installation group of 3 vessels total for floating

# WTIVs, feeders, num_feeders are for fixed bottom installations
# wtiv: floating_heavy_lift_vessel
# Module Specific
OffshoreSubstationInstallation:
  feeder: floating_barge
array_system:
  free_cable_length: 0.5
array_system_design:
  cables:
  # - XLPE_500mm_132kV # Updated to match FLORIS layout #XLPE_630mm_66kV # matches orca based on what I found
  - XLPE_185mm_66kV #TODO: Better understand which cables to use
  - XLPE_630mm_66kV
export_system_design:
  cables:
  - HVDC_2000mm_320kV # HVDC lines
  percent_added_length: 0.0
substation_design:
  floating_oss: True
mooring_system_design:
  num_lines: 3
  drag_embedment_fixed_length: 0
# Configured Phases
design_phases:
- ArraySystemDesign # from ORBIT/examples/configs/example_floating_project.yaml
- SemiSubmersibleDesign # from ORBIT/examples/configs/example_floating_project.yaml
- ElectricalDesign  # new addition from Sophie Bradenkamp combined ExportSystemDesign and OffshoreSubstationDesign phases
# - CustomArraySystemDesign
- SemiTautMooringSystemDesign  # MooringSystemDesign old system design could use for very deep water but out of date design
- OffshoreFloatingSubstationDesign
install_phases:
     # Define some dependent start times, ie, Array Cables start when Monopile are 100% complete
  ArrayCableInstallation: !!python/tuple
  - MonopileInstallation
  - 1.0
  ArrayCableInstallation: !!python/tuple
  - MooredSubInstallation
  - 0.5 # Start array cable installation when 50% of floaters are installed
  ExportCableInstallation: 0
  MooredSubInstallation: !!python/tuple
  - MooringSystemInstallation
  - 0.5 # Start substructure install when 50% of mooring lines installed
  MooringSystemInstallation: 0
  # OffshoreSubstationInstallation: !!python/tuple
  FloatingSubstationInstallation: !!python/tuple
  - ExportCableInstallation
  - 0.25 # Start OSS installation when 25% of cable installation is complete

substation_design:
  floating_oss: True
semisubmersible_design:
  stiffened_column_CR: 7000
substructure:
  takt_time: 168
  #unit_cost: 11757583 # USD, IEA VolutrnUS Reference Hull. Output from a run by Garret , Wisdem. 19 Aug 2022. 
# Wind Project Inputs
project_parameters:
  turbine_capex: 1300 # $USD turbine CAPEX only as per 2022 ATB https://atb.nrel.gov/electricity/2022/offshore_wind
  opex_rate: 100 # moderate Offshore Wind - Class 14 $USD/kW/yr ATB 2022, OpEx based on R&D assumptions with a base year of 2022.
  commissioning: 0.01 # ORBIT default
  decommissioning: 0.15 # ORBIT default
  grid_connection: False # option, can be turned on or off
  ppa_price: 0.025 # $/kWh based on 2022 land based wind market report (ERCOT area ppa prices) https://www.energy.gov/sites/default/files/2022-08/land_based_wind_market_report_2202.pdf
  solar: False
  project_lifetime: 30 # 2022 ATB capital recovery period for offshore wind
finance_parameters:
  general_inflation: 0.025 # based on 2022 ATB
  discount_rate: 0.0824 # HFTO discount rate. 10% nominal return based on 2022 ATB basline workbook
  debt_equity_split: 68.5 # 2022 ATB uses 68.5% debt # percent debt as per Avangrid 10-K is 50%. 
  property_tax: 0.01 # percent of CAPEX # combined with property insurance then between H2A and H2FAST defaults
  property_insurance: 0.005 # percent of CAPEX # combined with property tax then between H2A and H2FAST defaults
  total_income_tax_rate: 0.257 # 0.257 tax rate in 2022 atb baseline workbook # current federal income tax rate, but proposed 2023 rate is 0.28. No state income tax in Texas
  capital_gains_tax_rate: 0.15 # H2FAST default
  sales_tax_rate: 0.0 #Verify that a different rate shouldn't be used # minimum total sales tax rate in Corpus Christi https://www.cctexas.com/detail/corpus-christi-type-fund-purpose - does this apply to H2?
  debt_interest_rate: 0.055 #Interest rate reflective of current times
  debt_type: "Revolving debt" # can be "Revolving debt" or "One time loan". Revolving debt is H2FAST default and leads to much lower LCOH
  loan_period: 0 # H2FAST default, not used for revolving debt
  cash_onhand_months: 1 # H2FAST default
  administrative_expense_percent_of_sales: 0.00 #Check this # percent of sales H2FAST default
  depreciation_method: "MACRS" # can be "MACRS" or "Straight line" - straight line as per Avangrid 10-K, but MACRS may be better and can reduce LCOH by more than $1/kg and is spec'd in the IRS MACRS schedule https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
  depreciation_period: 5 # years - as specified by the IRS MACRS schedule https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
  depreciation_period_electrolyzer: 7 #This gets assigned differently in Kaitlin's run scenario but should be approx same # years based on PEM Electrolysis H2A Production Case Study Documentation estimate of 7 years. also see https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
  discount_years:
    wind: 2022 # based on turbine capex value provided to ORBIT from 2022 ATB
    wind_and_electrical: 2022 # for ORBIT opex
    platform: 2022 # TODO ask Nick and Charlie
    electrical_export_system: 2022 # also from ORBIT, so match wind assumptions. TODO ask Sophie Bradenkamp
    desal: 2013 # from code citation: https://www.nrel.gov/docs/fy16osti/66073.pdf
    electrolyzer: 2020 # for simple h2 cost model in hopp (see https://www.hydrogen.energy.gov/pdfs/19009_h2_production_cost_pem_electrolysis_2019.pdf) ## 2020 # based on IRENA report https://www.irena.org/-/media/Files/IRENA/Agency/Publication/2020/Dec/IRENA_Green_hydrogen_cost_2020.pdf
    h2_transport_compressor: 2016 # listed in code header 
    h2_storage:
      pressure_vessel: 2022 # based on readme for Compressed_gas_function
      pipe: 2019 # Papadias 2021
      salt_cavern: 2019 # Papadias 2021
      turbine: 2003 # assumed based on Kottenstette 2004
      none: 2022 # arbitrary
    h2_pipe_array: 2018 # ANL costs
    h2_transport_pipeline: 2018 # same model for costs as the h2_pipe_array
    pv: 2021
    wave: 2020

electrolyzer:
  rating: 996 # MW # 0.9*Plant rating appears near-optimal for 400 MW wind plant with 3 days of underground pipe storage # MW
  electrolyzer_capex: 1114 # $/kW conservative 2025 centralized. high 700, low 300 # based on https://www.irena.org/-/media/Files/IRENA/Agency/Publication/2020/Dec/IRENA_Green_hydrogen_cost_2020.pdf
  time_between_replacement: 62320 # 62320 based on PEM Electrolysis H2A Production Case Study Documentation estimate of 7 years, 40000 based on current est (see unpublished report), 80000 hours based on OSW atb_year = 2025
  replacement_cost_percent: 0.15 # percent of capex - H2A default case
  model: "singlitico2021" # Basic cost model based on H2a and HFTO program record for PEM electrolysis
# h2_transport_compressor:
#   output_pressure: 100 # bar (1 bar = 100 kPa)
#   flow_rate: 89 # kg/hr
#   energy_rating: 802 # kWe (aka 1 kWh)
#   mean_days_between_failures: 200 # days
#   useful_life: 15 # was default in compressor script
#   # annual_h2_throughput: 18750 # [kg/yr] -> kg of H2 per year 
h2_transport_compressor:
  outlet_pressure: 68 # bar based on HDSAM
h2_storage_compressor:
  output_pressure: 100 # bar (1 bar = 100 kPa)
  flow_rate: 89 # kg/hr
  energy_rating: 802 # kWe (aka 1 kWh)
  mean_days_between_failures: 200 # days
  # annual_h2_throughput: 18750 # [kg/yr] -> kg of H2 per year 
h2_transport_pipe:
  outlet_pressure: 10 # bar - from example in code from Jamie #TODO check this value
h2_storage:
  # capacity_kg: 18750 # kg
  capacity_from_max_on_turbine_storage: False # if True, then days of storage is ignored and storage capacity is based on how much h2 storage fits on the turbines in the plant using Kottenstete 2003.
  type: "pressure_vessel"#"none" # can be one of ["none", "pipe", "pressure_vessel", "salt_cavern"] ### not yet implemented:  ["line_rock_cavern"] #TODO fix salt cavern, just a number right now
  days: 3 # [days] how many days worth of production we should be able to store (this is ignored if `capacity_from_max_on_turbine_storage` is set to True)
platform:
  opex_rate: 0.0111 # % of capex to determine opex (see table 5 in https://www.acm.nl/sites/default/files/documents/study-on-estimation-method-for-additional-efficient-offshore-grid-opex.pdf)
  installation_days: 14 # days
policy_parameters: # these should be adjusted for inflation prior to application - order of operations: rate in 1992 $, 
#then prevailing wage multiplier if applicable, then inflation
  option1: # base # no policy included ---> see files/task1/regulation and policy revue/ page 4 of 13 middle - read this 
  # and look at assumptions
    wind_itc: 0
    wind_ptc: 0
    h2_ptc: 0
  option2: # base credit levels with H2
    wind_itc: 0
    wind_ptc: 0.003 # $0.003/kW (this is base, see inflation adjustment in option 3)
    h2_ptc: 0.6 # $0.60/kg h2 produced - assumes net zero but not meeting prevailing wage requirements - does this need to be 
    # adjusted for inflation from 2022 dollars to claim date, probably constant after claim date?
  option3: # same as option 5, but assuming prevailing wages are met --> 5x multiplier on both PTCs
    wind_itc: 0
    wind_ptc: 0.015 # $/kWh 1992 dollars
    h2_ptc: 3.00 # $/kg 2022 dollars - do not adjust for inflation
  # bonus options, option 5 and 6 but ITC equivalents
  option4: # prevailing wages not met
    wind_itc: 0.06 # %/100 capex
    wind_ptc: 0.00 # $/kW 1992 dollars
    h2_ptc: 0.6 # $0.60/kg produced 2022 dollars - assumes net zero but not meeting prevailing wage requirements - does this need to be 
    # do not adjust for inflation, probably constant after claim date?
  option5: # prevailing wages met
    wind_itc: 0.30 # %/100 capex
    wind_ptc: 0.0 # $/kWh 1992 dollars
    h2_ptc: 3.00 # $/kg of h2 produced 2022 dollars - do adjust for inflation every year applied and until application year
  option6: # assumes prevailing wages are met, and includes 10% bonus credit of domestic content (100% of steel and iron 
  # and mfg. components from the US)
    wind_itc: 0.40 # %/100 capex
    wind_ptc: 0.0 # $/kWh 1992 dollars
    h2_ptc: 3.00 # $/kg of h2 produced 2022 dollars - do adjust for inflation every year applied and until application year
  option7: # assumes prevailing wages are met, and includes 10% bonus credit of domestic content (100% of steel and iron 
  # and mfg. components from the US)
    wind_itc: 0.0 # %/100 capex
    wind_ptc: 0.0165 # $/kWh 1992 dollars (0.015*1.1)
    h2_ptc: 3.00 # $/kg of h2 produced 2022 dollars - do adjust for inflation every year applied and until application year
  # you can elect itc_for_h2 in leu of the h2_ptc - this choice is independent of the other tech credit selections
    # 6% or %50 for itc_for_h2

plant_design:
  scenario0:
    electrolyzer_location: "platform" # can be one of ["onshore", "turbine", "platform"]
    transportation: "pipeline" # can be one of ["hvdc", "pipeline", "none"]
    h2_storage_location: "platform" # can be one of ["onshore", "turbine", "platform"]
  scenario1:
    electrolyzer_location: "onshore" # can be one of ["onshore", "turbine", "platform"]
    transportation: "hvdc" # can be one of ["hvdc", "pipeline", "none"]
    h2_storage_location: "onshore" # can be one of ["onshore", "turbine", "central_platform"]
  scenario2:
    electrolyzer_location: "onshore" # can be one of ["onshore", "turbine", "platform"]
    transportation: "hvdc" # can be one of ["hvdc", "pipeline", "none"]
    h2_storage_location: "platform" # can be one of ["onshore", "turbine", "central_platform"]
  scenario3:
    electrolyzer_location: "turbine" # can be one of ["onshore", "turbine", "platform"]
    transportation: "none" # can be one of ["hvdc", "pipeline", "none"]
    h2_storage_location: "turbine" # can be one of ["onshore", "turbine", "central_platform"]
  scenario4:
    electrolyzer_location: "turbine" # can be one of ["onshore", "turbine", "platform"]
    transportation: "none" # can be one of ["hvdc", "pipeline", "none"]
    h2_storage_location: "platform" # can be one of ["onshore", "turbine", "central_platform"]
  scenario5:
    electrolyzer_location: "turbine" # can be one of ["onshore", "turbine", "platform"]
    transportation: "pipeline" # can be one of ["hvdc", "pipeline", "none"]
    h2_storage_location: "onshore" # can be one of ["onshore", "turbine", "central_platform"]
  scenario6:
    electrolyzer_location: "platform" # can be one of ["onshore", "turbine", "platform"]
    transportation: "none" # can be one of ["hvdc", "pipeline", "none"]
    h2_storage_location: "platform" # can be one of ["onshore", "turbine", "central_platform"]
  scenario7:
    electrolyzer_location: "platform" # can be one of ["onshore", "turbine", "platform"]
    transportation: "pipeline" # can be one of ["hvdc", "pipeline", "none"]
    h2_storage_location: "onshore" # can be one of ["onshore", "turbine", "central_platform"]

# design A -> scenario 1
    # onshore electrolysis 
    # HVDC transport, HVDC_2000mm_320kV
    # no storage
# design B -> scenario 7
    # electrolysis on platform
    # pipe transport to shore
    # no storage